title: Omar Brkan
description: Eseji, proza, kritika i poezija
author: Omar Brkan
email: brkano@email.com

markdown: kramdown
encoding: utf-8
kramdown:
  input: GFM
  hard_wrap: false

baseurl: ""
# Globalni permalink za POSTOVE (ostavite kako je bilo, ali ga čistimo)
permalink: /:categories/:title/
future: false
show_excerpts: true

# --- ISPRAVKA JE OVDE ---
jekyll-category-pages:
  layout: default
  # Koristimo siguran slug i prefiks 'kategorija-' za stranice kategorija
  permalink: /kategorija-:slug/

defaults:
  -
    scope:
      path: ""
      type: "pages"
    values:
      layout: "default"
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
