title: Omar Brkan 
description: Eseji, proza, kritika i poezija
author: Omar Brkan
email: brkano@gmail.com  


theme: jekyll-theme-minimal 
baseurl: "" 


permalink: /:categories/:title/
future: false
show_excerpts: true


jekyll-category-pages:
  layout: default
  permalink: /:category/
